package boundary;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aquario
 */
public class painelSairTrabalhoAluno {

    /**
     * Creates new form painelCriarTGAluno
     */
    public painelSairTrabalhoAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        painelSairTrabalhoAluno = new javax.swing.JPanel();
        lblSairTrabalho_TelaSairTrabalhoAluno = new javax.swing.JLabel();

        painelSairTrabalhoAluno.setBackground(new java.awt.Color(255, 255, 255));
        painelSairTrabalhoAluno.setMinimumSize(new java.awt.Dimension(100, 100));

        lblSairTrabalho_TelaSairTrabalhoAluno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSairTrabalho_TelaSairTrabalhoAluno.setText("Deseja realmente sair do grupo de trabalho de graduação?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(painelSairTrabalhoAluno);
        painelSairTrabalhoAluno.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSairTrabalho_TelaSairTrabalhoAluno)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblSairTrabalho_TelaSairTrabalhoAluno)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblSairTrabalho_TelaSairTrabalhoAluno.getAccessibleContext().setAccessibleName("lblSairTrabalho_TelaSairTrabalhoAluno");
        
        painelSairTrabalhoAluno.setBackground(new Color(215, 215, 250));
        painelSairTrabalhoAluno.getAccessibleContext().setAccessibleName("painelConsultarBancaAluno");
    }// </editor-fold>                        


    // Variables declaration - do not modify         
    public javax.swing.JPanel painelSairTrabalhoAluno;
    private javax.swing.JLabel lblSairTrabalho_TelaSairTrabalhoAluno;
    // End of variables declaration                   
}
