package boundary;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aquario
 */
public class painelCriarPerfilAluno implements ActionListener{

    /**
     * Creates new form painelCriarTGAluno
     */
    public painelCriarPerfilAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        
        painelCriarPerfilAluno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelFormCriarPerfilAluno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEditarEmailAluno_TelaCriarPerfilAluno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNomeAluno_TelaCriarPerfilAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRAAluno_TelaCriarPerfilAluno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCursoAluno_TelaCriarPerfilAluno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmailAluno_TelaCriarPerfilAluno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSenhaAluno_TelaCriarPerfilAluno = new javax.swing.JTextField();
        btnEditarSenhaAluno_TelaCriarPerfilAluno = new javax.swing.JButton();

        painelCriarPerfilAluno.setBackground(new java.awt.Color(255, 255, 255));
        painelCriarPerfilAluno.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("PERFIL");

        painelFormCriarPerfilAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        painelFormCriarPerfilAluno.setPreferredSize(new java.awt.Dimension(943, 441));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Dados Pessoais e de Acesso");

        btnEditarEmailAluno_TelaCriarPerfilAluno.setBackground(new java.awt.Color(102, 102, 102));
        btnEditarEmailAluno_TelaCriarPerfilAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarEmailAluno_TelaCriarPerfilAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEmailAluno_TelaCriarPerfilAluno.setText("Editar E-mail");
        btnEditarEmailAluno_TelaCriarPerfilAluno.addActionListener(this);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        txtNomeAluno_TelaCriarPerfilAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeAluno_TelaCriarPerfilAluno.setText("Nome do aluno");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("R.A.:");

        txtRAAluno_TelaCriarPerfilAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRAAluno_TelaCriarPerfilAluno.setText("0000000000000");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Curso:");

        txtCursoAluno_TelaCriarPerfilAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCursoAluno_TelaCriarPerfilAluno.setText("Nome do Curso");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("E-mail:");

        txtEmailAluno_TelaCriarPerfilAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmailAluno_TelaCriarPerfilAluno.setText("email_do_aluno@email.com");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Senha:");

        txtSenhaAluno_TelaCriarPerfilAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSenhaAluno_TelaCriarPerfilAluno.setText("***************");

        btnEditarSenhaAluno_TelaCriarPerfilAluno.setBackground(new java.awt.Color(102, 102, 102));
        btnEditarSenhaAluno_TelaCriarPerfilAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarSenhaAluno_TelaCriarPerfilAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarSenhaAluno_TelaCriarPerfilAluno.setText("Editar Senha");
        btnEditarSenhaAluno_TelaCriarPerfilAluno.addActionListener(this);

        javax.swing.GroupLayout painelFormCriarPerfilAlunoLayout = new javax.swing.GroupLayout(painelFormCriarPerfilAluno);
        painelFormCriarPerfilAluno.setLayout(painelFormCriarPerfilAlunoLayout);
        painelFormCriarPerfilAlunoLayout.setHorizontalGroup(
            painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                .addGroup(painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSenhaAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEditarSenhaAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(txtEmailAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnEditarEmailAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(7, 7, 7)
                                .addComponent(txtCursoAluno_TelaCriarPerfilAluno))
                            .addGroup(painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtRAAluno_TelaCriarPerfilAluno))
                            .addGroup(painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeAluno_TelaCriarPerfilAluno))
                            .addGroup(painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
        );
        painelFormCriarPerfilAlunoLayout.setVerticalGroup(
            painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFormCriarPerfilAlunoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRAAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCursoAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmailAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarEmailAluno_TelaCriarPerfilAluno))
                .addGap(18, 18, 18)
                .addGroup(painelFormCriarPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSenhaAluno_TelaCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarSenhaAluno_TelaCriarPerfilAluno))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        btnEditarEmailAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleName("btnEditarEmailAluno_TelaCriarPerfilAluno");
        btnEditarEmailAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleDescription("");
        txtNomeAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleName("txtNomeAluno_TelaCriarPerfilAluno");
        txtNomeAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleDescription("");
        jLabel4.getAccessibleContext().setAccessibleDescription("");
        txtRAAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleName("txtRAAluno_TelaCriarPerfilAluno");
        txtRAAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleDescription("");
        txtCursoAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleName("txtCursoAluno_TelaCriarPerfilAluno");
        txtEmailAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleName("txtEmailAluno_TelaCriarPerfilAluno");
        txtSenhaAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleName("txtSenhaAluno_TelaCriarPerfilAluno");
        btnEditarSenhaAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleName("btnEditarSenhaAluno_TelaCriarPerfilAluno");
        btnEditarSenhaAluno_TelaCriarPerfilAluno.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(painelCriarPerfilAluno);
        painelCriarPerfilAluno.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(painelFormCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelFormCriarPerfilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("lblCriarTG");
        painelFormCriarPerfilAluno.getAccessibleContext().setAccessibleName("painelFormCriarPerfilAluno");
        painelFormCriarPerfilAluno.getAccessibleContext().setAccessibleDescription("");
        txtCursoAluno_TelaCriarPerfilAluno.setEditable(false);
        txtEmailAluno_TelaCriarPerfilAluno.setEditable(false);
        txtNomeAluno_TelaCriarPerfilAluno.setEditable(false);
        txtRAAluno_TelaCriarPerfilAluno.setEditable(false);
        txtSenhaAluno_TelaCriarPerfilAluno.setEditable(false);

        painelCriarPerfilAluno.getAccessibleContext().setAccessibleName("painelCriarPerfilAluno");
    }// </editor-fold>                        

    public void telaEditarEmailAluno(){
        JOptionPane.showOptionDialog(null, // parent
				new painelEditarEmailAluno().painelEditarEmailAluno,                                                    // object
				"Editar E-mail",                                                         // title
				JOptionPane.DEFAULT_OPTION,                 // option type
				JOptionPane.QUESTION_MESSAGE,           // message type
				new ImageIcon(),                                                           // icon
				new String[] {"Cancelar", "Confirmar"},			          // options[]
				"Cancel");
    }
    
    public void telaEditarSenhaAluno(){
        JOptionPane.showOptionDialog(null, // parent
				new painelEditarSenhaAluno().painelEditarSenhaAluno,                                                    // object
				"Editar Senha do Usuário",                                                         // title
				JOptionPane.DEFAULT_OPTION,                 // option type
				JOptionPane.QUESTION_MESSAGE,           // message type
				new ImageIcon(),                                                           // icon
				new String[] {"Cancelar", "Confirmar"},			          // options[]
				"Cancel");
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnEditarEmailAluno_TelaCriarPerfilAluno;
    private javax.swing.JButton btnEditarSenhaAluno_TelaCriarPerfilAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel painelFormCriarPerfilAluno;
    public javax.swing.JPanel painelCriarPerfilAluno;
    private javax.swing.JTextField txtCursoAluno_TelaCriarPerfilAluno;
    private javax.swing.JTextField txtEmailAluno_TelaCriarPerfilAluno;
    private javax.swing.JTextField txtNomeAluno_TelaCriarPerfilAluno;
    private javax.swing.JTextField txtRAAluno_TelaCriarPerfilAluno;
    private javax.swing.JTextField txtSenhaAluno_TelaCriarPerfilAluno;
    // End of variables declaration                   

    public void actionPerformed(ActionEvent e) {
        if ("Editar E-mail".equals(e.getActionCommand()))
            telaEditarEmailAluno();
         
         if ("Editar Senha".equals(e.getActionCommand()))
            telaEditarSenhaAluno();
    }
}